In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('/home/users/cturrell/documents/eddy_feedback/b-parameter/cmip6_b/hist_NaN_issues/nan_counts_all_models.csv')
df

           model               var  perc_nan
0     ACCESS-CM2        ucomp_orig    0.9230
1     ACCESS-CM2        ucomp_anom    0.9230
2     ACCESS-CM2      div1_QG_orig    1.1529
3     ACCESS-CM2      div1_QG_anom    1.1529
4     ACCESS-CM2  div1_QG_123_orig   22.3441
..           ...               ...       ...
227  UKESM1-0-LL      div1_QG_anom    1.1494
228  UKESM1-0-LL  div1_QG_123_orig   22.4553
229  UKESM1-0-LL  div1_QG_123_anom   22.4553
230  UKESM1-0-LL  div1_QG_gt3_orig   22.4553
231  UKESM1-0-LL  div1_QG_gt3_anom   22.4553

[232 rows x 3 columns]

In [10]:
df2 = pd.read_csv('/home/users/cturrell/documents/eddy_feedback/b-parameter/cmip6_b/hist_NaN_issues/hist_processing_results.csv')

In [11]:
df = df.merge(df2[['model', 'status']], on='model', how='left')
df[df['var'] == 'div1_QG_123_orig'].reset_index(drop=True)

                model               var  perc_nan   status
0          ACCESS-CM2  div1_QG_123_orig   22.3441  success
1       ACCESS-ESM1-5  div1_QG_123_orig   22.0595  success
2      AWI-ESM-1-1-LR  div1_QG_123_orig    2.7776   failed
3         BCC-CSM2-MR  div1_QG_123_orig    0.0000  success
4        CMCC-CM2-HR4  div1_QG_123_orig    0.0000  success
5        CMCC-CM2-SR5  div1_QG_123_orig    0.0000  success
6       CNRM-CM6-1-HR  div1_QG_123_orig   38.1382   failed
7           EC-Earth3  div1_QG_123_orig    0.0000  success
8   EC-Earth3-AerChem  div1_QG_123_orig    0.0000  success
9        EC-Earth3-CC  div1_QG_123_orig    0.0000  success
10        FGOALS-f3-L  div1_QG_123_orig   26.8519   failed
11           GFDL-CM4  div1_QG_123_orig   22.3601  success
12          GFDL-ESM4  div1_QG_123_orig   22.3361  success
13        GISS-E2-1-G  div1_QG_123_orig   37.9900   failed
14    HadGEM3-GC31-LL  div1_QG_123_orig   32.9684  success
15    HadGEM3-GC31-MM  div1_QG_123_orig   36.0460   failed
16          KIOST-ESM  div1_QG_123_orig    0.0000  success
17         MIROC-ES2L  div1_QG_123_orig   21.4245  success
18             MIROC6  div1_QG_123_orig   34.6835   failed
19    MPI-ESM-1-2-HAM  div1_QG_123_orig    0.0000  success
20      MPI-ESM1-2-HR  div1_QG_123_orig    0.0000  success
21      MPI-ESM1-2-LR  div1_QG_123_orig    0.0000  success
22         MRI-ESM2-0  div1_QG_123_orig   36.9526   failed
23              NESM3  div1_QG_123_orig    0.0000  success
24         NorESM2-LM  div1_QG_123_orig    0.0000  success
25         NorESM2-MM  div1_QG_123_orig    0.0000  success
26        SAM0-UNICON  div1_QG_123_orig   25.9905   failed
27            TaiESM1  div1_QG_123_orig    0.0000  success
28        UKESM1-0-LL  div1_QG_123_orig   22.4553  success